## Don't change this value!
config-version: 1




## The amount of hours everyone starts off with
start-time-in-hours: 24




boogeyman:
  ## The amount of time it takes for the boogeyman to actually be rolled
  ## after running the command
  roll-delay-in-minutes: 10

  ## The maximum and minimum amount of boogeymen that are able to be chosen
  ## Set both to the same value to force a certain amount
  amount-max: 1
  amount-min: 1

  ## The amount of time gained when a boogeyman secures a kill (in seconds)
  time-gain-on-boogey-kill: 3600

  ## The amount of time lost when someone gets killed by a boogeyman (in seconds)
  time-lost-on-boogey-death: 7200

  ## Determines whether red names can be chosen as a boogeyman
  red-boogeymen: false




penalties:
  ## The amount of time players lose upon dying (in seconds)
  time-lost-on-death: 3600

rewards:
  ## The amount of time players upon killing someone (in seconds)
  time-gain-on-kill: 1800




recipes:
  ## Creates a new recipe for tnt which replaces most of the gunpowder required with paper
  paper-tnt: true
  ## Makes it so that helmets are unobtainable
  disable-helmets: true
  ## Makes it so that bookshelves are unobtainable
  disable-bookshelves: true
  craftable-saddle: true
  craftable-name-tag: true




enchantment-table:
  craftable: true

  ## Only change the following two settings if you want the table to not be craftable!
  breakable: true

  ## Makes every enchantment table on the ground immortal and unable to be despawned when enabled.
  ## E.x. it won't burn in lava and can't be blown up.
  indestructible-on-drop: false




## Determines whether enchantments will be nerfed when applied to an item.
anvil:
  stacking-nerf: true
  level-limit: 1




name-colour-thresholds:
  ## The amount of time the player needs to have less than in order to become a red name (in seconds)
  ## default: 28800 (8 hours)
  red-name: 28800

  ## The amount of time the player needs to have less than in order to become a yellow name (in seconds)
  ## default: 57600 (16 hours)
  yellow-name: 57600




custom-chat-format:
  enabled: false
  ## Make sure to include 'player' and 'message' in the format, as they are placeholders!
  format: "player: message"