## Set to -1 in order to disable configuration update reminders
config-version: 2




timer:
  ## The amount of hours everyone starts off with
  start-time-in-hours: 24

  ## When set to true, players who join the server late will have their time set to a fair
  ## amount automatically
  balanced-time-for-latecomers: true




boogeyman:
  ## The amount of time it takes for the boogeyman to actually be rolled
  ## after running the command
  roll-delay-in-minutes: 10

  ## Determines whether reminders will be sent out to everyone.
  ## I recommend disabling this if the roll-delay-in-minutes is set to less than 10.
  reminders: true

  ## The maximum and minimum amount of boogeymen that are able to be chosen
  ## Set both to the same value to force a certain amount
  amount-max: 1
  amount-min: 1

  ## The amount of time gained when a boogeyman secures a kill (in seconds)
  time-gain-on-boogey-kill: 3600

  ## The amount of time lost when someone gets killed by a boogeyman (in seconds)
  time-lost-on-boogey-death: 7200

  ## Determines whether red names can be chosen as a boogeyman
  red-boogeymen: true




penalties:
  ## The amount of time players lose upon dying (in seconds)
  time-lost-on-death: 3600

  ## Determines whether players will lose time when killed by someone with the same
  ## name colour as them (doesn't apply to red names)
  subtract-time-on-death-same-colour: true




rewards:
  ## The amount of time players upon killing someone (in seconds)
  time-gain-on-kill: 1800

  ## Determines whether players will receive time when they kill someone with
  ## the same name colour as them (doesn't apply to red names)
  add-time-on-kill-same-colour: true




name-colour-thresholds:
  ## The amount of time the player needs to have less than in order to become a red name (in seconds)
  ## default: 28800 (8 hours)
  red-name: 28800

  ## The amount of time the player needs to have less than in order to become a yellow name (in seconds)
  ## default: 57600 (16 hours)
  yellow-name: 57600




## Please note that the following settings only get applied while in survival mode. ###################### !!! ######################
recipes:
  ## The following five settings determine whether the listed items are craftable, able to be picked up, or able to be interacted with in an inventory
  helmets-unobtainable: true
  bookshelves-unobtainable: true
  netherite-unobtainable: false
  golden-apples-unobtainable: false
  enchanted-golden-apples-unobtainable: true

  ## Creates a new recipe for tnt which replaces most of the gunpowder required with paper
  paper-tnt: true

  ## Determines whether saddles and/or name tags are craftable
  craftable-saddle: true
  craftable-name-tag: true
  craftable-slimeball: false



## Please note that the following settings only get applied while in survival mode. ###################### !!! ######################
enchantment-table:
  craftable: true

  ## I recommend only changing the following two settings if you don't want the table to be craftable!
  breakable: true

  ## Makes every enchantment table on the ground immortal and unable to be despawned when enabled.
  ## E.x. it won't burn in lava and can't be blown up.
  indestructible-on-drop: false




## Determines whether enchantments will be nerfed when applied to an item.
anvil:
  stacking-nerf: false
  level-limit: 1




## You may whitelist potions by adding their enum name to the list.
## For help, refer to the wiki: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionType.html
## Please note that the following settings only get applied while in survival mode. ###################### !!! ######################
potion-whitelist:
  enabled: false
  list:
    - WATER
    - AWKWARD
    - MUNDANE
    - INVISIBILITY
    - SPEED
    - FIRE_RESISTANCE
    - NIGHT_VISION
    - JUMP
    - WATER_BREATHING




custom-chat-format:
  enabled: false
  ## Make sure to include 'player' and 'message' in the format, as they are placeholders!
  format: "player: message"




other:
  ## Determines whether a lighting sound will be played when someone runs out of time
  lightning-sound-on-final-death: true

  ## Determines whether a message will be sent out to all other admins whenever someone runs a command
  ## Example: [Alex: Added 30 minutes to Steve's timer]
  command-feedback: true

  ## Determines whether the plugin should print out an update reminder upon every startup/reload
  ## whenever there's one available
  plugin-update-reminders: true